fix: changed search_node action to determine correct index
kyazdani42/nvim-tree.lua pull request #1022
Opened 2022-02-25 18:16 UTC by be-ndee

see #1014

2022-02-28 20:17 UTC, kyazdani42 requested changes
looks good to me, except those comments are not needed :)

2022-02-28 20:17 UTC, kyazdani42 commented on lua/nvim-tree/actions/search-node.lua
> +  -- ask user for path
please remove these comments, we can read the code well :smile:

2022-02-28 20:17 UTC, kyazdani42 commented on lua/nvim-tree/actions/search-node.lua
> +        -- e.g. user searches for "/foo/bar.txt", than directory "/foo/bar" should not match with filename
You can keep only the 2nd line of the comment :)

2022-02-28 20:17 UTC, kyazdani42 commented on lua/nvim-tree/actions/search-node.lua
> +    return index;
leading `;` not needed

2022-03-01 07:02 UTC, be-ndee commented
I've done the requested changes :)

2022-03-01 18:56 UTC, kyazdani42 approved these changes

2022-03-01 18:56 UTC, merged