feat: new config to be able to always open the tree on setup
kyazdani42/nvim-tree.lua pull request #1023
Opened 2022-02-25 18:24 UTC by be-ndee

2022-02-28 20:22 UTC, kyazdani42 requested changes

2022-02-28 20:22 UTC, kyazdani42 commented on lua/nvim-tree.lua
> +  -- evaluate open_on_setup configs
Uneeded comment

2022-02-28 20:22 UTC, kyazdani42 commented on lua/nvim-tree.lua
> +      if buf_is_dir or buf_is_empty then
incorrect indent level

2022-03-01 07:02 UTC, be-ndee commented
I've done the requested changes :)

2022-03-01 18:55 UTC, kyazdani42 approved these changes

2022-03-01 18:56 UTC, merged