Feat - add hooks to config
kyazdani42/nvim-tree.lua pull request #1151
Opened 2022-04-10 15:48 UTC by HPRIOR

Add 'open' and 'close' callbacks or 'hooks' which can be set during setup and which fire when toggling the sidebar. 

This can be used to interact with other plugins. For example, the position of a tab bar can be changed according to the width of the file tree when it is opened or closed.

2022-04-11 00:43 UTC, alex-courtis requested changes
Please document in help and readme.

See CONTRIBUTING.md

2022-04-11 00:45 UTC, alex-courtis requested changes

2022-04-11 00:45 UTC, alex-courtis commented on lua/nvim-tree.lua
> +  close_hook = function () end,
Please default these to nil and run `update-default-opts.sh`.

2022-04-11 00:54 UTC, alex-courtis commented
I think @HPRIOR has started something big that will grow.

Let's name configs so that we can add to it. Perhaps:
```lua
  hooks = {
    node_open = nil,
    node_close = nil,
  },
```

Maybe `actions.hooks`.

@kyazdani42 you have name ideas ;)

2022-04-11 01:07 UTC, alex-courtis requested changes
These should be nvim-tree.events e.g. `nvim-tree.events.on_nvim_tree_open`

We could pass the node, like action callbacks.

2022-04-11 08:01 UTC, HPRIOR commented
Hey @alex-courtis, I'll implement the suggested changes soon. 

With regard to your previous comment (I'm not sure where it has gone) an additional section in the config would be a good idea if 'hooks' are to be added elsewhere.  Something like:

```lua
hooks = {
    tree_open = nil,
    tree_close = nil,
},
```
Would it be possible to explain how the event system works?

2022-04-12 18:40 UTC, kyazdani42 reviewed
you don't need to setup the hooks yourself, the user will call the the event registration himself, no need to set it during setup :)

2022-04-12 20:15 UTC, kyazdani42 commented
i'm not even sure you placed the event at the right location to be honest :smile: i think i would place them in view.lua. There are multiple ways the tree can be opened, it won't just work by setting it in toggle :)

2022-04-12 21:58 UTC, HPRIOR commented
@kyazdani42 thanks for your feedback. I have moved the event dispatches to `view.lua`. Let me know if there is anything else I can do. If the code is not to your liking otherwise, I would really like to see this feature at some point!

2022-04-14 00:15 UTC, alex-courtis commented
> With regard to your previous comment an additional section in the config would be a good idea

That was a mistake on my part... before I realised that we should use events ;)

2022-04-14 00:16 UTC, alex-courtis requested changes
We need to document this in the help: nvim-tree.events

2022-04-14 20:31 UTC, HPRIOR commented
> We need to document this in the help: nvim-tree.events

I've added the documentation

2022-04-15 00:45 UTC, alex-courtis approved these changes

2022-04-18 13:41 UTC, kyazdani42 approved these changes

2022-04-18 13:41 UTC, merged

2022-04-18 16:58 UTC, gegoune commented
Another useful event would be `on_tree_leave` (or similar) for when window is not closed but no longer active.

2022-04-19 19:18 UTC, kyazdani42 commented
what do you mean no longer active ? when the tree buffer is replaced by a file buffer ?

2022-04-19 20:06 UTC, gegoune commented
Apologies for not being clear. I mean event when cursor leaves nvim-tree window. Wither because file was opened or by any window movement, such as `<C-w><C-w>`.

2022-04-20 19:42 UTC, kyazdani42 commented
well...
```
au WinLeave NvimTree_* ...
```
?

2022-04-20 20:46 UTC, gegoune commented
Absolutely, that's what I have at the moment, and with on open event I can replace one of autocmds, but only one. Leaving tree remains as autocmd rather than event, which feels bit odd.

2022-04-21 18:05 UTC, kyazdani42 commented
Well i'm not sure how it would be different inside the plugin ^^'

2022-04-21 18:07 UTC, gegoune commented
That's absolutely alright, just thought that it could make events more complete. I am fine sticking to auto commands.

2022-04-21 18:14 UTC, kyazdani42 commented
:smile: now you can define autocmd in lua with callbacks so i think it doesn't matter too much :)

2022-04-21 18:15 UTC, gegoune commented
And this is exactly what I have. Thanks though and apologies for the noise. :)