feat: wrapped the setup recall guard in an option
kyazdani42/nvim-tree.lua pull request #1333
Opened 2022-06-10 19:05 UTC by dominicpalmer

Following points raised in https://github.com/kyazdani42/nvim-tree.lua/issues/1313, this change wraps the setup call guard (from https://github.com/kyazdani42/nvim-tree.lua/commit/b1ecb75a6cf0bc83ec64d987c7f4128ada3c254e) in an option named `suppress_setup_recall_warning`.

While it makes sense to inform the user that they shouldn't recall `setup`, forcibly warning them every time via the UI is intrusive. 

Note that this PR doesn't alter the default behaviour of always warning. The user must explicitly set `suppress_setup_recall_warning` to `true` to suppress the messages.

2022-06-11 03:55 UTC, alex-courtis requested changes
Please update :help as per readme.

Please run update-default-opts as per https://github.com/kyazdani42/nvim-tree.lua/blob/master/CONTRIBUTING.md

2022-06-11 03:55 UTC, alex-courtis commented on README.md
> +Setup may only be run once; subsequent calls will result in a warning. Do not invoke from, say, a packer config function and then call it again later. You can suppress the warning using the `suppress
Let's be explicit:

"Setup may only be run once; subsequent calls will be a NOP will result in a warning."

2022-06-11 03:55 UTC, alex-courtis commented on lua/nvim-tree.lua
> +    return
We should return even when `suppress_setup_recall_warning` is set.

nvim-tree will behave unpredictably (duplicate autocommands etc) when setup is run twice.

2022-06-11 09:25 UTC, dominicpalmer commented
Ran update-default-opts, updated help, updated readme wording, and switched to always returning early even if the warning is suppressed.

2022-06-11 10:27 UTC, kylo252 reviewed
Please switch to using the builtin logger, where the user can set the level once for all errors/warnings/info/debug/trace.

are you going to create a suppress flag for each new warning you add?

every instance of `util.warn` should be replaced with `log[LEVEL](...)` instead

--- 

Furthermore, this is just an implementation detail about allowing to call `setup()` multiple times or not, so it should be a debug entry and not a warning (since there's nothing to do about it, unless you meant it as a breaking change, which you should've clarified in https://github.com/kyazdani42/nvim-tree.lua/pull/1308 and marked it as such)

2022-06-11 10:27 UTC, kylo252 commented on README.md
> +  suppress_setup_recall_warning = false,
```suggestion
```

2022-06-11 10:27 UTC, kylo252 commented on doc/nvim-tree-lua.txt
> +      suppress_setup_recall_warning = false,
```suggestion
```

2022-06-11 10:27 UTC, kylo252 commented on doc/nvim-tree-lua.txt
> +
```suggestion
```

2022-06-11 10:27 UTC, kylo252 commented on lua/nvim-tree.lua
> +  suppress_setup_recall_warning = false,
```suggestion
```

2022-06-11 10:27 UTC, kylo252 commented on lua/nvim-tree.lua
> +    end
```suggestion
utils.warn "nvim-tree.lua setup called multiple times"
```

2022-06-11 13:47 UTC, dominicpalmer commented
> are you going to create a suppress flag for each new warning you add?

I didn't add the warning. The addition of a suppression flag was to honour @alex-courtis's original change, while giving the user the option to no longer see the warning. My original argument was to remove the guard altogether and instead focus on allowing config change without restarting, but I know that's a bigger undertaking.

@kylo252 - I've replaced the call to `utils.warn` with a log write and removed the option

2022-06-12 01:41 UTC, alex-courtis commented
> Please switch to using the builtin logger, where the user can set the level once for all errors/warnings/info/debug/trace.
> ...
> every instance of `util.warn` should be replaced with `log[LEVEL](...)` instead

The logger is for diagnostic purposes only, when reporting an issue. It is not enabled by default and we do not expect the user to look at the log under normal operations.

> are you going to create a suppress flag for each new warning you add?

Warnings are explicit and the user is expected to resolve them. This suppression is unique and applies for a specific and exceptional use case.

> Furthermore, this is just an implementation detail about allowing to call `setup()` multiple times or not, so it should be a debug entry and not a warning (since there's nothing to do about it, unless you meant it as a breaking change, which you should've clarified in #1308 and marked it as such)

Calling setup multiple times resulted in nvim-tree behaving unexpectedly and incorrectly. Many users raised issues following multiple setups, resolved by removing the extra calls to setup.

#1308 was not a breaking change. It was a bug fix that prevented the incorrect / unexpected behaviour. The warning was added so that the (many) users experiencing such problems were alerted to them and could resolve them without needing to raise an issue.

The most common problem case: user calls setup with no options via packer config. User calls setup again with their options. nvim-tree runs with mostly defaults and many of the user's options not applied.

2022-06-12 01:53 UTC, alex-courtis requested changes
Change approved after reverting bd7a941

2022-06-12 02:06 UTC, alex-courtis commented
Raised #1338 

It is not a trivial amount of work, however would satisfy all users.

2022-06-12 10:52 UTC, dominicpalmer commented
Alright. If the suppression will get approved as-is then I'm for it. I'm representing the user here, and frankly, any short term fix that stops the message getting displayed everytime I hot reload my config, I'm all for it. Now that #1338 is raised there's an incentive for a full fix to be worked on regardless.

2022-06-12 11:03 UTC, kyazdani42 commented
i've opened #1340 which should make setup work as expected, thus not needing this PR. 
Can you guys check it and report any inconsistent behavior you might observe ?

2022-06-26 10:14 UTC, kyazdani42 commented
closing in favor of merged #1340

2022-06-26 10:14 UTC, closed without merging