feat: add cwd arg and fallback to open_replacing_current_buffer
kyazdani42/nvim-tree.lua pull request #1348
Opened 2022-06-15 05:59 UTC by javiertury

Make `open_replacing_current_buffer` reach feature parity with `open`

- Accept `cwd` argument
- Fallback to `vim.loop.cwd()` instead of `return`

2022-06-18 07:03 UTC, alex-courtis requested changes
Looks good, works.

2022-06-18 07:03 UTC, alex-courtis commented on lua/nvim-tree.lua
> +    if bufname ~= "" and vim.loop.fs_stat(bufname) ~= nil then
Let's retain the existing behaviour of returning early when this is false.

2022-06-18 10:22 UTC, kyazdani42 approved these changes
LGTM

2022-06-19 03:59 UTC, alex-courtis approved these changes

2022-06-19 03:59 UTC, merged