feat(live_filter): filter nodes from loaded buffers
kyazdani42/nvim-tree.lua pull request #1446
Opened 2022-07-21 09:52 UTC by kyazdani42

Breaking: changing `f` binding to `ff` for the input type filter
Adding `fb` for buffer type filter.

Note: if folders are not shown (`:help nvim-tree.live_filter.always_show_folders`), the filter will not find the nodes since these will be filtered out. 
This option will only work well with find_files enabled and always_show_folders true.

We need to improve the filter algorithm to be able to search recursively. The UI can also be improved for the buffer filtering, something like displaying the buffer number. But this will come in other PRs

2022-07-23 01:39 UTC, alex-courtis commented on doc/nvim-tree-lua.txt
> +    { key = "ff",                             action = "live_filter" }
On pressing ff when fb is active, the filter changes text to `/Buffer/` which is not useful.

2022-07-23 01:40 UTC, alex-courtis commented
> We need to improve the filter algorithm to be able to search recursively.

I'd like that for regular filter. Out of scope here.

2022-07-23 01:47 UTC, alex-courtis requested changes
Functionality is useful, works.

The UX is not great. We do not need to present this functionality to the user as a filter, even if we do it that way internally.

Proposal:
- leave existing `f` and `F` unchanged
  - avoids breaking change
- use `B` to toggle buffer filtering, like `H` `I` etc
  - `B` will not show `[FILTER]: /Buffer/` as this is confusing
- `f` and `B` may be run together, like `f` and `H`

There is no indication that `B` is on, but that is OK as there is no indication that `H` is on. Users appear happy with that.

2022-07-26 09:16 UTC, kyazdani42 commented
After your comments, i wonder if this feature should even be inside the live-filter :smile: I think we could just implement this filter on the renderer since we already check for opened buffers there.

2022-07-26 09:17 UTC, kyazdani42 commented
Also this might be a good idea to do like neo-tree and display the buf numbers next to the filenames.
I'm closing in favor of a better implementation.

2022-07-26 09:17 UTC, closed without merging