fixing the call to vim.fn.system
kyazdani42/nvim-tree.lua pull request #1550
Opened 2022-08-24 00:15 UTC by Xyhlon

it is not desired to call vim.fn.system("whole command"), hence it takes all the output of the shell, there might be undesired info be parsed into the string aswell. see https://github.com/kyazdani42/nvim-tree.lua/issues/1547 for more info.
better way of calling vim.fn.system({"whole","command"}) only this way the desired output of the command can be guarantied.

2022-08-27 03:03 UTC, alex-courtis commented
Related: https://github.com/kyazdani42/nvim-tree.lua/issues/1484

Prior art neotree: https://github.com/nvim-neo-tree/neo-tree.nvim/commit/b30a418275e748a6833996a9c655bb107aae2034

2022-08-27 03:17 UTC, alex-courtis requested changes
Thanks for looking at this one.

Needs work.

Fix should also be applied to `should_show_untracked`

2022-08-27 03:17 UTC, alex-courtis commented on lua/nvim-tree/git/utils.lua
>    log.line("git", cmd)
cmd is unused.

Please replace cmd with `{ "git", "-C", vim.fn.shellescape(cwd), "rev-parse", "--show-toplevel" }`, log it and and pass it to `vim.fn.system(`

2022-08-27 03:17 UTC, alex-courtis commented on lua/nvim-tree/git/utils.lua
> +  local toplevel = vim.fn.system { "git", "-C", vim.fn.shellescape(cwd), "rev-parse", "--show-toplevel" }
This fails:
```
[2022-08-27 13:15:55] [profile] START git toplevel /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon
[2022-08-27 13:15:55] [git] git -C '/home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon' rev-parse --show-toplevel
fatal: cannot change to ''/home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon'': No such file or directory
[2022-08-27 13:15:55] [profile] END   git toplevel /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon  2ms
```

master:
```
[2022-08-27 13:15:28] [profile] START git toplevel /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon
[2022-08-27 13:15:28] [git] git -C '/home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon' rev-parse --show-toplevel
/home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon
[2022-08-27 13:15:28] [profile] END   git toplevel /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon  8ms
[2022-08-27 13:15:28] [profile] START git untracked /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon
[2022-08-27 13:15:28] [git] git -C /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon config status.showUntrackedFiles
[2022-08-27 13:15:28] [profile] END   git untracked /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon  7ms
[2022-08-27 13:15:28] [profile] START git job /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon nil
[2022-08-27 13:15:28] [git] running job with timeout 400ms
[2022-08-27 13:15:28] [git] git --no-optional-locks status --porcelain=v1 --ignored=matching -u
!! doc/tags
[2022-08-27 13:15:28] [git] done
[2022-08-27 13:15:28] [profile] END   git job /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon nil  4ms
[2022-08-27 13:15:28] [git] job success    /home/alex/.local/share/nvim/vundle/nvim-tree.lua.Xyhlon nil
```

```lua
log = {
      enable = true,
      truncate = true,
      types = {
        git = true,
        profile = true,
      },
    }
```

2022-09-10 02:17 UTC, alex-courtis commented
/nudge @Xyhlon 

This will fix issues that many users are experiencing.

2022-09-21 11:33 UTC, Xyhlon reviewed
if you remove vim.fn.shellescape from cwd in the cmd everything works without the fatal error message

2022-09-21 23:12 UTC, alex-courtis commented
> if you remove vim.fn.shellescape from cwd in the cmd everything works without the fatal error message

That sounds reasonable. It seems that cwd is being passed as an argument rather than to the command line, so no need to escape.

To validate and test:
* a variety of cwd that include spaces and a variety of special characters e.g. `#` that would normally need to be escaped
* MacOS
* Windows WSL, powershell etc. (no developer available)

2022-09-22 01:17 UTC, alex-courtis commented
I've merged master and applied the fix to toplevel, as well as untracked.

I cannot push to your repo. Please grant me access or merge master and apply 
[0001-fix-1547-pass-git-toplevel-cwd-unescaped-pass-git-un.patch.txt](https://github.com/kyazdani42/nvim-tree.lua/files/9621372/0001-fix-1547-pass-git-toplevel-cwd-unescaped-pass-git-un.patch.txt)

2022-09-23 01:55 UTC, alex-courtis commented
I'm tempted to change the "msys2 git support" path, however the escaping seems fragile and I have no way to test it.

2022-09-23 01:59 UTC, alex-courtis commented
This should "resolve"
#1585
#1586 
#1484 
https://github.com/kyazdani42/nvim-tree.lua/issues/549#issuecomment-1127394585
and others

2022-09-24 13:53 UTC, Xyhlon commented
applied patch and access granted

2022-09-25 02:56 UTC, alex-courtis commented
Merged and pushed to your fork.

Tested a variety of cases with paths that we would normally escape; everything working as expected without `vim.fn.shellescape`.

Merging PR now.

2022-09-25 02:58 UTC, merged

2022-09-25 02:59 UTC, alex-courtis commented
Many thanks for driving this change; this has been problematic for some time.