fix(#1555): incorrect exe highlight in Windows filesystem from WSL
kyazdani42/nvim-tree.lua pull request #1557
Opened 2022-08-26 19:27 UTC by doanamo

Resolves #1555

2022-08-27 03:44 UTC, alex-courtis requested changes
- [ ] test io.open result

Reviewed but not tested: no available windows environment.

All codepaths but `is_wsl` guarded by windows checks and will be accepted without verification.

2022-08-27 03:44 UTC, alex-courtis commented on lua/nvim-tree/explorer/node-builders.lua
> +    local proc_version = io.open("/proc/version"):read("*a")
Blows up when not found. Set to `io.open("/procccccccccc/version")`.

Need to test the results of io.open.

```
Error executing vim.schedule lua callback: ...vt-dev/site/pack/packer/start/packer.nvim/lua/packer.lua:339: Vim(lua):E5108: Error executing lua ...ree.lua.doanamo/lua/nvim-tree/explorer/node-builders.lua:8: attempt to index a nil value
stack traceback:
        ...ree.lua.doanamo/lua/nvim-tree/explorer/node-builders.lua:8: in function <...ree.lua.doanamo/lua/nvim-tree/explorer/node-builders.lua:7>
        ...ree.lua.doanamo/lua/nvim-tree/explorer/node-builders.lua:10: in main chunk
        [C]: in function 'require'
        ...nvim-tree.lua.doanamo/lua/nvim-tree/explorer/explore.lua:4: in main chunk
        [C]: in function 'require'
        ...rt/nvim-tree.lua.doanamo/lua/nvim-tree/explorer/init.lua:9: in main chunk
        [C]: in function 'require'
        ...acker/start/nvim-tree.lua.doanamo/lua/nvim-tree/core.lua:2: in main chunk
        [C]: in function 'require'
        ...rt/nvim-tree.lua.doanamo/lua/nvim-tree/renderer/init.lua:1: in main chunk
        [C]: in function 'require'
        ...packer/start/nvim-tree.lua.doanamo/lua/nvim-tree/lib.lua:3: in main chunk
        [C]: in function 'require'
        ...ack/packer/start/nvim-tree.lua.doanamo/lua/nvim-tree.lua:4: in main chunk
        [C]: in function 'require'
        /tmp/nvt-dev.lua:32: in function 'setup'
        [string ":lua"]:1: in main chunk
        [C]: in function 'cmd'
        ...vt-dev/site/pack/packer/start/packer.nvim/lua/packer.lua:339: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'cmd'
        ...vt-dev/site/pack/packer/start/packer.nvim/lua/packer.lua:339: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

2022-08-27 03:45 UTC, alex-courtis commented
`:help has` indicates that "wsl" is a possibility; can you use that?

2022-08-27 03:49 UTC, alex-courtis commented on lua/nvim-tree/explorer/node-builders.lua
> +    local proc_version = io.open("/proc/version"):read("*a")
This handle must be closed.

2022-08-27 11:26 UTC, doanamo commented
Updated with following changes:
* Use `has "wsl"` as suggested
* Close `io.popen` handles
* Greatly improved performance by reducing the amount of `wslpath` calls using lazy evaluation and making calls for parents of file nodes (directories/links) instead of for each file
  * Tested performance by navigating directories such as `/usr/bin/` and `C:\Windows\System32`
* Fix reported code style

Thank you for your review!

2022-08-27 11:49 UTC, doanamo commented
Updated again:
* I've forgot to update a call to `is_executable()` after changing its signature which resulted in errors on reloading tree view
* I wasn't properly calling `close()` on handles

2022-08-28 02:22 UTC, alex-courtis requested changes
Everything is guarded behind `is_wsl` and `is_windows`.

I cannot test; assuming that this works. Please be available to resolve any issues that users report.

- [ ] [luadoc](https://keplerproject.github.io/luadoc/manual.html) for new utils

2022-08-28 02:22 UTC, alex-courtis commented on lua/nvim-tree/explorer/node-builders.lua
> +  is_wsl = vim.fn.has "wsl" == 1,
:+1:

2022-08-28 02:22 UTC, alex-courtis commented on lua/nvim-tree/explorer/node-builders.lua
> +      -- Evaluate lazily when needed and do so only once for each parent
:+1:

2022-08-28 02:22 UTC, alex-courtis commented on lua/nvim-tree/utils.lua
> +function M.is_wsl_windows_fs_path(path)
Please add doc to both these methods as per `is_windows_exe`

2022-08-28 02:23 UTC, alex-courtis commented
tip: you can run the linter locally: [CONTRIBUTING.md](https://github.com/kyazdani42/nvim-tree.lua/blob/master/CONTRIBUTING.md)

git-hooks are optional but useful

2022-08-28 11:16 UTC, doanamo commented
Updated with luadoc comments and style fixes

2022-08-28 11:31 UTC, doanamo commented
> Please be available to resolve any issues that users report.

Sure thing! Feel free to ping me in any case that may seem related to my changes. 👍

2022-08-29 00:41 UTC, alex-courtis commented
> > Please be available to resolve any issues that users report.
> 
> Sure thing! Feel free to ping me in any case that may seem related to my changes. +1

Thank you. If there's any issue we will mention you.

2022-08-29 00:53 UTC, alex-courtis approved these changes

2022-08-29 00:53 UTC, merged