fixes #175 | early return if internal state is invalid(does not match…
kyazdani42/nvim-tree.lua pull request #177
Opened 2021-01-13 09:31 UTC by davidsu

… nvim's state

2021-01-13 10:15 UTC, davidsu commented on lua/lib/renderer.lua
> +  if not is_bufnr_valid(bufnr) then return end
this was throwing on re-source of init.vim

2021-01-13 11:12 UTC, akinsho commented
@davidsu I'm definitely keen for a fix, looking at this does it stop the tree from being opened or drawn? I'm guessing not as when I tend to get this error nvim tree isn't even open so I'm guessing its during the `BufEnter` autocommand where this is failing (This is me just asking out of curiosity).

2021-01-13 11:34 UTC, davidsu commented
The tree opens properly.

2021-01-15 18:29 UTC, kyazdani42 requested changes

2021-01-15 18:29 UTC, kyazdani42 commented on lua/lib/renderer.lua
> +  if not is_bufnr_valid(tree.bufnr) then return end
could you just add an empty line between these two function. Also declaring is_bufnr_valid as local to avoid conflicts :)

2021-01-17 22:28 UTC, kyazdani42 approved these changes

2021-01-17 22:28 UTC, merged