Patch windows
kyazdani42/nvim-tree.lua pull request #222
Opened 2021-03-06 21:14 UTC by pudymody

Hi, i found your plugin on Reddit and i liked its simplicity! Good job.
Sadly in my try to test it, i found out that it wasnt able to execute on windows.

Here is a patch for that.
I dont know if EVERYTHING is working, but basic navigation, creation of folder/files, copy/cut and deletion was working on my tests.

It also checks that the current version of Neovim is at least 0.5, otherwise it doesnt load itself.

Solves: #208

2021-03-06 22:29 UTC, pudymody commented
I've just found out that git integration doesnt work, so i think its not ready to merge yet.
Im sorry i havent tested it enough.

2021-03-06 22:34 UTC, kyazdani42 commented
cool thanks :) tell me when you're done i'll review the code still works on linux too !

2021-03-06 22:56 UTC, pudymody commented
Now everything should work as expected.

2021-03-07 10:56 UTC, kyazdani42 requested changes
I think the path_separator code is called many times, it could be loaded only once and accessed through it's own module, providing functions like `join_path`. Also why package.config instead of `vim.fn.has('win32') and '\\' or '/'` ? could windows have `/` path separators ?

2021-03-07 10:56 UTC, kyazdani42 commented on lua/nvim-tree/git.lua
> +
this file is not properly indented

2021-03-08 02:41 UTC, pudymody commented
> Also why package.config instead of `vim.fn.has('win32') and '\\' or '/'`

No particular reason, i just prefer lua to tell me what the separator is, instead of defining it myself.

> could windows have / path separators ?

In windows the '/' character is used to separate folders/files, but i liked the consistency of having all the paths with '\\' and not mix between both.

As per the module, is it okay if i put it as a function inside the utils module?

2021-03-08 17:13 UTC, kyazdani42 commented
allright, yes go for it

2021-03-08 17:55 UTC, pudymody commented
Done :)

2021-03-08 20:50 UTC, kyazdani42 requested changes
one last small thing and we're good to go. I'm testing this PR on linux in the meanwhile to make sure nothing was broke

2021-03-08 20:50 UTC, kyazdani42 commented on lua/nvim-tree/git.lua
> +  local is_win = vim.api.nvim_call_function("has", {"win32"})
you could call this function only once, not on very create_root call :)

2021-03-08 20:55 UTC, kyazdani42 commented
This break git integration on linux not sure why

2021-03-09 01:14 UTC, pudymody commented
You were absolutely right, i was silly and forgot to check that the condition was true. (i thought that it returned an integer).
Now everything should be working again.

2021-03-09 08:19 UTC, kyazdani42 commented
looks good, thanks for working on that. You can also update the README and the doc file to remove the `not working on windows` information and i'll merge this :)

2021-03-09 19:12 UTC, merged

2021-03-09 19:12 UTC, kyazdani42 commented
thanks for the contribution !