Added new option, respect_buf_cwd
kyazdani42/nvim-tree.lua pull request #533
Opened 2021-07-29 02:19 UTC by ucchiee

Added a new option that respect the current buffer's cwd. Nvim-tree changes its cwd to that of buffer's when this option is enabled and nvim-tree is opened.

This ensures that the cwd of nvim-tree is same as that of buffer's.

2021-07-29 02:22 UTC, ucchiee commented
For those who want to use this option:

Install from my repo
```
Plug 'ucchiee/nvim-tree.lua', {'branch': 'ucchiee/feature/option/respect_buf_cwd'}
```
and enable the option
```
let g:nvim_tree_respect_buf_cwd = 1
```

2021-08-02 18:59 UTC, kyazdani42 requested changes
missing a doc description :)

2021-08-03 23:44 UTC, ucchiee commented
Thank you, updated the doc.

2021-08-07 07:59 UTC, kyazdani42 approved these changes

2021-08-07 07:59 UTC, merged