feat(diagnostics): Support coc as diagnostic source(#555)
kyazdani42/nvim-tree.lua pull request #556
Opened 2021-08-10 07:11 UTC by xiyaowong

If you don't like it, just close the pr :)

2021-08-10 22:16 UTC, kyazdani42 requested changes

2021-08-10 22:16 UTC, kyazdani42 commented on lua/nvim-tree/diagnostics.lua
> +  local source = vim.g.nvim_tree_lsp_diagnostics_source or 'nvim_lsp'
couldn't you just detect if the user uses nvim_lsp or coc ? something like checking `vim.fn.exists('g:did_coc_loaded')` so we don't add additional configuration options :)

2021-08-10 22:16 UTC, kyazdani42 commented on lua/nvim-tree/diagnostics.lua
> +  for bufname, severty_list in pairs(diagnostics) do
severity

2021-08-11 00:28 UTC, xiyaowong commented
I made some changes:)

2021-08-14 09:00 UTC, kyazdani42 approved these changes

2021-08-14 09:00 UTC, merged